### CreateTodo
POST http://localhost:5271/todoitems
Content-Type: application/json

{
  "name": "test todo item again",
  "isComplete": false
}

### GetAllTodos
GET http://localhost:5271/todoitems


### GetTodo
GET http://localhost:5271/todoitems/1


### GetCompleteTodos
GET http://localhost:5271/todoitems/complete


### UpdateTodo
PUT http://localhost:5271/todoitems/10
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

### DeleteTodo
DELETE http://localhost:5271/todoitems/1